/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CardType = IDL.Variant({
  'faq' : IDL.Null,
  'aiops' : IDL.Null,
  'help' : IDL.Null,
  'greeting' : IDL.Null,
  'incident' : IDL.Null,
  'confirmation' : IDL.Null,
  'project' : IDL.Null,
});
export const Card = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'cardType' : CardType,
  'image' : IDL.Text,
  'subtitle' : IDL.Text,
  'header' : IDL.Text,
});

export const idlService = IDL.Service({
  'getGreetingCard' : IDL.Func([], [Card], []),
  'getStaticAvatar' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat8)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CardType = IDL.Variant({
    'faq' : IDL.Null,
    'aiops' : IDL.Null,
    'help' : IDL.Null,
    'greeting' : IDL.Null,
    'incident' : IDL.Null,
    'confirmation' : IDL.Null,
    'project' : IDL.Null,
  });
  const Card = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'cardType' : CardType,
    'image' : IDL.Text,
    'subtitle' : IDL.Text,
    'header' : IDL.Text,
  });
  
  return IDL.Service({
    'getGreetingCard' : IDL.Func([], [Card], []),
    'getStaticAvatar' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat8)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };